theme: minima
title: Learning GitHub Pages
author: Wesley Murray
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is my second GitHub page. My first was from when I was learning markdown. This page is where I am experimenting to learn GitHub Pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
